import env from '@/utils/env'

export const API_BASE_URL = `${env.VITE_SERVER_API_URL}${env.VITE_SERVER_API_PREFIX ?? '/api'}` as const
export const API_TIMEOUT = env.VITE_SERVER_API_TIMEOUT
export const TOKEN_HEADER_NAME = env.VITE_AUTH_TOKEN_HEADER_NAME
export const TOKEN_HEADER_PREFIX = env.VITE_AUTH_TOKEN_HEADER_PREFIX
export const COMPATIBILITY_TOKEN_HEADER_NAME = env.VITE_AUTH_COMPATIBILITY_TOKEN_HEADER_NAME
export const COMPATIBILITY_TOKEN_HEADER_ENABLED = env.VITE_AUTH_COMPATIBILITY_TOKEN_HEADER_ENABLED
